export const menuImages = {
  "12 Piece Wings Combo": "/menu/12-piece-wings-combo.jpg",
  "24 Piece Wings Combo": "/menu/24-piece-wings-combo.jpg",
  "Achari Cauliflower": "/menu/achari-cauliflower.jpg",
  "Achari Wings": "/menu/achari-wings.jpg",
  "BBQ Chicken Combination": "/menu/bbq-chicken-combination.jpg",
  "BBQ Sauce": "/menu/bbq-sauce.png",
  "BBQ Wings": "/menu/bbq-wings.jpg",
  "Boneless BBQ Wings": "/menu/boneless-bbq-wings.jpg",
  "Boneless Buffalo Hot Wings": "/menu/boneless-buffalo-hot-wings.jpg",
  "Boneless Honey Sriracha Wings": "/menu/boneless-honey-sriracha-wings.jpg",
  "Boneless Mango Habanero Wings": "/menu/boneless-mango-habanero-wings.jpg",
  "Boneless Tandoori Wings": "/menu/boneless-tandoori-wings.jpg",
  "Brownie (8\")": "/menu/brownie-8.jpg",
  "Buffalo Chicken": "/menu/buffalo-chicken.jpg",
  "Buffalo Hot Wings": "/menu/buffalo-hot-wings.jpg",
  "Butter Achari Cauliflower": "/menu/butter-achari-cauliflower.jpg",
  "Butter Chicken": "/menu/butter-chicken.jpg",
  "Butter Chicken Halal Pizza": "/menu/butter-chicken-halal-pizza.jpg",
  "Chicken Bacon Supreme": "/menu/chicken-bacon-supreme.jpg",
  "Chicken Caesar Salad": "/menu/chicken-caesar-salad.png",
  "Chicken Tikka": "/menu/chicken-tikka.jpg",
  "Chicken Tikka Halal Pizza": "/menu/chicken-tikka-halal-pizza.jpg",
  "Chocolate Chip Cookie (8\")": "/menu/chocolate-chip-cookie-8.jpg",
  "Classic Veggie": "/menu/classic-veggie.jpg",
  "Classic Veggie Vegan": "/menu/classic-veggie-vegan.jpg",
  "Combination": "/menu/combination.jpg",
  "Craft Your Own": "/menu/craft-your-own.jpg",
  "Curry Chicken": "/menu/curry-chicken.jpg",
  "Curry Chicken Halal Pizza": "/menu/curry-chicken-halal-pizza.jpg",
  "Curry Wings": "/menu/curry-wings.jpg",
  "Desi BBQ Paneer": "/menu/desi-bbq-paneer.jpg",
  "Garden Delight": "/menu/garden-delight.jpg",
  "Garlic Bread with Cheese": "/menu/garlic-bread-with-cheese.jpg",
  "Garlic Bread with Jalape\u00f1os and Pineapple": "/menu/garlic-bread-with-jalapenos-and-pineapple.jpg",
  "Garlic Chicken Supreme": "/menu/garlic-chicken-supreme.jpg",
  "Halal Pepperoni Pizza": "/menu/halal-pepperoni-pizza.jpg",
  "Hawaiian": "/menu/hawaiian.jpg",
  "Honey Sriracha Wings": "/menu/honey-sriracha-wings.jpg",
  "Hot Sauce": "/menu/hot-sauce.png",
  "Indian Veggie": "/menu/indian-veggie.jpg",
  "Indian Veggie Vegan": "/menu/indian-veggie-vegan.jpg",
  "Jain Paneer": "/menu/jain-paneer.jpg",
  "Jain Veggie": "/menu/jain-veggie.jpg",
  "Jalapeno Ranch": "/menu/jalapeno-ranch.png",
  "Kids CYO Pizza": "/menu/kids-cyo-pizza.jpg",
  "Kids Pepperoni Pizza": "/menu/kids-pepperoni-pizza.jpg",
  "Lemon Pepper Wings": "/menu/lemon-pepper-wings.jpg",
  "Malai Chicken": "/menu/malai-chicken.jpg",
  "Malai Chicken Halal Pizza": "/menu/malai-chicken-halal-pizza.jpg",
  "Malai Paneer": "/menu/malai-paneer.jpg",
  "Mango Habanero Wings": "/menu/mango-habanero-wings.jpg",
  "Margherita Pizza": "/menu/margherita-pizza.jpg",
  "Marinara Sauce": "/menu/marinara-sauce.png",
  "Meat Fiesta": "/menu/meat-fiesta.jpg",
  "Mexicano": "/menu/mexicano.jpg",
  "Pepperoni Pizza": "/menu/pepperoni-pizza.jpg",
  "Pesto Chicken": "/menu/pesto-chicken.jpg",
  "Pesto Sticks": "/menu/pesto-sticks.jpg",
  "Potato Chips": "/menu/potato-chips.jpg",
  "Ranch": "/menu/ranch.png",
  "Tandoori BBQ Chicken": "/menu/tandoori-bbq-chicken.jpg",
  "Tandoori Chicken": "/menu/tandoori-chicken.jpg",
  "Tandoori Chicken Halal Pizza": "/menu/tandoori-chicken-halal-pizza.jpg",
  "Tandoori Wings": "/menu/tandoori-wings.jpg",
  "Veg Extravaganza": "/menu/veg-extravaganza.jpg",
  "Veg Extravaganza Vegan": "/menu/veg-extravaganza-vegan.jpg",
  "Water": "/menu/water.png",
};

export function menuImage(name) {
  return menuImages[name] ?? null;
}

export const featuredImages = {
  "indian": "/menu/butter-chicken.jpg",
  "classics": "/menu/margherita-pizza.jpg",
  "starters": "/menu/pesto-sticks.jpg",
  "dietary": "/menu/jain-paneer.jpg",
};
